# Run from top of vpp repo with command:
# docker build -f extras/docker/Dockerfile.test -t vppbuild .
FROM debian:sid-slim
ADD . /src/vpp
WORKDIR /src/vpp
RUN apt-get update
RUN apt-get -y install make sudo git curl build-essential libelf-dev libbpf-dev
RUN UNATTENDED=y make install-dep
CMD ["/bin/bash"]
